akaka0039/Global_Developer_site

src/app/Http/Controllers/EventController.php
src/app/Http/Requests/StoreEventRequest.php
src/app/Models/Event.php
src/app/Providers/RouteServiceProvider.php
src/database/seeders/EventsTableSeeder.php
src/resources/js/Pages/Main/Index.jsx
src/routes/web.php

- create CRUD function for events table
- add the setting of seeder

Create CRUD function for events table

---

src/app/Http/Requests/StoreEventRequest.php
src/app/Models/Event.php
src/app/Models/User.php
src/resources/js/Pages/Event/EventForm.jsx
src/resources/js/Pages/Event/TimeForm.jsx

- add relationship between users and events table
- connect to back end for create event function
- add error messages
fixed #55 fixed #57

Fix issue 55

---

.github/PULL_REQUEST_TEMPLATE.md
src/app/Http/Controllers/EventController.php
src/app/Http/Middleware/HandleInertiaRequests.php
src/resources/js/Pages/Main/Index.jsx

- fix bug for event edit action
- add flash message
- add PR　template
fixed #56

Fix issue 56

---

src/app/Http/Controllers/EventController.php
src/app/Http/Controllers/ParticipantController.php
src/app/Models/Event.php
src/app/Models/User.php
src/resources/js/Pages/Event/EventDetail.jsx
src/routes/web.php

- create the controller for participants
- add the relationship for participants table
- 
fixed #77

Add relationship for participants table

---

src/resources/js/Layouts/GuestLayout.jsx
src/resources/js/Pages/Auth/Login.jsx

fix layout:
・GuestLayout.jsx
・login.jsx
819ae85)
fixed
all fixed by improving a GuestLayout.jsx

Fix layout login register

---

src/app/Http/Controllers/EventController.php
src/app/Http/Controllers/ProfileController.php
src/app/Models/Event.php
src/app/Models/User.php
src/resources/js/Pages/Profile/ProfileDetail.jsx
src/routes/web.php

- create routing for the profile page
- create the data set for the profile page
- fix some bugs
fixed #92

Provide data for profile page

---

src/app/Http/Controllers/EventController.php
src/app/Http/Controllers/ParticipantController.php
src/app/Http/Requests/StoreEventRequest.php
src/app/Models/Event.php
src/app/Models/User.php
src/composer.json
src/composer.lock
src/config/tags.php
src/database/migrations/2023_06_16_225955_drop_tags_table.php
src/database/migrations/2023_06_16_225956_drop_event_tags_table.php
src/database/migrations/2023_06_16_231537_create_tag_tables.php
src/database/migrations/2023_06_17_212204_create_wait_lists_table.php
src/database/seeders/DatabaseSeeder.php
src/database/seeders/TagsTableSeeder.php
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventForm.jsx

Create wait list function

---

src/app/Http/Controllers/EventController.php
src/app/Http/Controllers/ParticipantController.php
src/app/Http/Requests/StoreEventRequest.php
src/app/Models/Event.php
src/composer.json
src/composer.lock
src/config/tags.php
src/database/migrations/2023_06_16_225955_drop_tags_table.php
src/database/migrations/2023_06_16_225956_drop_event_tags_table.php
src/database/migrations/2023_06_16_231537_create_tag_tables.php
src/database/seeders/DatabaseSeeder.php
src/database/seeders/TagsTableSeeder.php
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventForm.jsx

- create tags function
- fix the way to get participant data as async in the event detail
- create seeder file for tags
fixed #95

Added tag function

---

src/app/Http/Controllers/EventController.php
src/app/Http/Controllers/ParticipantController.php
src/app/Http/Requests/StoreEventRequest.php
src/app/Models/Event.php
src/app/Models/User.php
src/composer.json
src/composer.lock
src/config/tags.php
src/database/migrations/2023_06_16_225955_drop_tags_table.php
src/database/migrations/2023_06_16_225956_drop_event_tags_table.php
src/database/migrations/2023_06_16_231537_create_tag_tables.php
src/database/migrations/2023_06_17_212204_create_wait_lists_table.php
src/database/seeders/DatabaseSeeder.php
src/database/seeders/TagsTableSeeder.php
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventForm.jsx

Merged PRs in the waitlist by mistake, so re-created them.
fixed

add tag and wait list function

---

docker-compose.yml
docker/app/Dockerfile
src/package-lock.json

・add phpMyAdmin #110
・update version nodeJs & npm #116 
fixed

add phpMyadmin #110 & fix #116

---

src/resources/js/Pages/Event/EventDetail.jsx

Fix bug of attend button

---

src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventFormComponents/MemberPopup.jsx

・Fix layout 
・Match data between front and back side #79
・Add Member popup page from attendance or people in wait list #126
Fixed
Add

#79 & #126

---

src/app/Http/Controllers/EventController.php
src/app/Http/Controllers/ParticipantController.php
src/app/Http/Controllers/ProfileController.php
src/app/Http/Requests/ProfileUpdateRequest.php
src/app/Http/Requests/StoreEventRequest.php
src/resources/js/Layouts/GeneralLayout.jsx
src/resources/js/Layouts/GuestLayout.jsx
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventForm.jsx
src/resources/js/Pages/Event/EventFormComponents/TimeForm.jsx
src/resources/js/Pages/Profile/Edit.jsx
src/resources/js/Pages/Profile/Partials/ProfileEdit.jsx
src/resources/js/Pages/Profile/ProfileDetail.jsx
src/resources/js/app.jsx
src/routes/web.php

Create edit page for event
fixed #122 #111 #98 #123 #111

Fix issue 98

---

src/app/Http/Requests/ProfileUpdateRequest.php
src/app/Models/User.php
src/resources/js/Pages/Profile/Partials/ProfileEdit.jsx

・fix layout 
・add function to delete a image #119 
・add a column of position #131  
・fix console log error #132 
・fix deleting image after reloading #133 
fixed
add

fix #119 #131 #132 #133

---

src/app/Http/Controllers/EventController.php
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventFormComponents/TimeForm.jsx
src/resources/js/Pages/Main/Index.jsx

- add a feature to filter events by tags
- fixed the bug for end_date
fixed #136 fixed #137

Add filter feature by tags

---

src/app/Models/Event.php
src/app/Models/User.php
src/database/migrations/2023_06_23_004225_add_column_soft_deletes_users_table.php
src/database/migrations/2023_06_23_021449_add_column_soft_deletes_events_table.php

Add soft delete function for users and events tables

---

src/app/Http/Controllers/EventController.php
src/app/Http/Requests/StoreEventRequest.php
src/app/Models/Event.php
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventForm.jsx

- fix logic to attach participants to the event.
- fix the display for attend button
fixed #104

FIx logic to create participant

---

src/resources/js/Components/Dropdown.jsx
src/resources/js/Components/Header.jsx
src/resources/js/Components/Sidebar.jsx
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventFormComponents/MemberPopup.jsx
src/resources/js/Pages/Main/Card.jsx
src/resources/js/Pages/Main/Index.jsx
src/resources/js/Pages/Main/MainCard.jsx

・fix main page #85 #118 
・add pop page on #138 
・click out of the member pop page to close #146  
fixed
add

Fix issues #85

---

src/resources/js/Components/FlashMessage.jsx
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Main/Index.jsx
src/resources/js/Pages/Main/MainCard.jsx
src/resources/js/Pages/Profile/DetailComponent/OrganizingEvents.jsx
src/resources/js/Pages/Profile/DetailComponent/ParticipatingEvents.jsx
src/resources/js/Pages/Profile/Partials/ProfileEdit.jsx
src/resources/js/Pages/Profile/ProfileDetail.jsx
src/resources/js/Pages/Top/Top_1.jsx
src/resources/js/Pages/Top/Top_2.jsx
src/resources/js/Pages/Top/Top_3.jsx
src/routes/web.php

- fix profile detail page #145 
- fix route of profile show page #128 
- arrange that host can only see edit button #130 
- fix that main card covers on sidebar #153 
- fix that flash message covers on sidebar #154 
- fix sentences of top page #151 
fixed

Fix issues #145

---

src/app/Http/Controllers/EventController.php
src/resources/js/Components/footer.jsx
src/resources/js/Pages/Contact/Index.jsx
src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Event/EventForm.jsx
src/resources/js/Pages/Profile/Partials/ProfileEdit.jsx
src/resources/js/Pages/Top/Top_2.jsx
src/routes/web.php

- fix event form to display a image #162 
- not to show past events #163
- fix layout of footer #150 
- add a contact us page #158
- can see image on event form page if there is the data in db #162
- no past events in main page #163
fixed
adde

#fix issues #162

---

src/resources/js/Components/Header.jsx
src/resources/js/Components/footer.jsx
src/resources/js/Pages/Top/Index.jsx
src/resources/views/app.blade.php
src/tailwind.config.js

Revamped top page design
fixed

Fix layout for top page

---

README.md
src/resources/js/app.jsx
src/vite.config.js

- fix app.jsx #172
- improve read.me #167 
- check no console error #159
fixed

edit to deploy

---

src/resources/js/Pages/Main/Index.jsx

Change design of event list page

---

src/resources/js/Components/Button.jsx
src/resources/js/Pages/Event/EventForm.jsx
src/resources/js/Pages/Event/EventFormComponents/AddressForm.jsx
src/resources/js/Pages/Event/EventFormComponents/TimeForm.jsx
src/tailwind.config.js

Fix layout event create and edit

---

src/package-lock.json
src/package.json
src/resources/js/Pages/Main/Index.jsx
src/resources/js/app.jsx
src/tailwind.config.js

As the title says
https://github.com/akaka0039/Global_Developer_site/assets/46436794/a7d54f66-f509-4ccb-b166-1b8ebcd3ccae
fixed

Add drop down for tag filter

---

src/resources/js/Pages/Event/EventDetail.jsx
src/resources/js/Pages/Profile/ProfileDetail.jsx
src/resources/views/app.blade.php

- add Font Awesome & fix icon on event detail page 
- fix layout a user detail page
oper_site/assets/40246308/73ab937a-c12f-48f0-aa73-513307f9601b)
fixed

Add font awesome
